track-stock-market-momentum/Models/ErrorViewModel.cs
namespace track_stock_market_momentum.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

track-stock-market-momentum/Models/StockTrade.cs
namespace track_stock_market_momentum.Models
{
    /// <summary>
    /// Represents the model class to supply trade details (stock id, stock name, price and quantity etc.) to the Trade/Index view
    /// </summary>
    public class StockTrade
    {
        public string? StockSymbol { get; set; }
        public string? StockName { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
    }
}

track-stock-market-momentum/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using track_stock_market_momentum.Models;

namespace track_stock_market_momentum.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Route("/")]
        [Route("/Home")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("/Home/Privacy")]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

track-stock-market-momentum/Controllers/TradeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using ServiceContracts;
using track_stock_market_momentum;
using track_stock_market_momentum.Models;

namespace StockMarketSolution.Controllers
{
 [Route("[controller]")]
 public class TradeController : Controller
 {
  private readonly TradingOptions _tradingOptions;
  private readonly IFinnhubService _finnhubService;
  private readonly IConfiguration _configuration;


  /// <summary>
  /// Constructor for TradeController that executes when a new object is created for the class
  /// </summary>
  /// <param name="tradingOptions">Injecting TradeOptions config through Options pattern</param>
  /// <param name="stocksService">Injecting StocksService</param>
  /// <param name="finnhubService">Injecting FinnhubService</param>
  /// <param name="configuration">Injecting IConfiguration</param>
  public TradeController(IOptions<TradingOptions> tradingOptions, IFinnhubService finnhubService, IConfiguration configuration)
  {
   _tradingOptions = tradingOptions.Value;
   _finnhubService = finnhubService;
   _configuration = configuration;
  }


  [Route("/Trade")]
  [Route("[controller]/[action]")]
  [Route("~/[controller]/[action]")]
  public IActionResult Index()
  {
   //reset stock symbol if not exists
   if (string.IsNullOrEmpty(_tradingOptions.DefaultStockSymbol))
    _tradingOptions.DefaultStockSymbol = "MSFT";


   //get company profile from API server
   Dictionary<string, object>? companyProfileDictionary = _finnhubService.GetCompanyProfile(_tradingOptions.DefaultStockSymbol);

   //get stock price quotes from API server
   Dictionary<string, object>? stockQuoteDictionary = _finnhubService.GetStockPriceQuote(_tradingOptions.DefaultStockSymbol);


   //create model object
   StockTrade stockTrade = new StockTrade() { StockSymbol = _tradingOptions.DefaultStockSymbol };

   //load data from finnHubService into model object
   if (companyProfileDictionary != null && stockQuoteDictionary != null)
   {
    stockTrade = new StockTrade() { StockSymbol = Convert.ToString(companyProfileDictionary["ticker"]), StockName = Convert.ToString(companyProfileDictionary["name"]), Price = Convert.ToDouble(stockQuoteDictionary["c"].ToString()) };
   }

   //Send Finnhub token to view
   ViewBag.FinnhubToken = _configuration["FinnhubToken"];

   return View(stockTrade);
  }
 }
}

track-stock-market-momentum/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

track-stock-market-momentum/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrackStockMarketMomentum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TrackStockMarketMomentum.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">TrackStockMarketMomentum</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TrackStockMarketMomentum - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

track-stock-market-momentum/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    ViewData["CurrentUrl"] = Url.Action("Index", "Home");
}



<section id="hero">
    <div class="grid-layout">
        <div class="grid-item left-column">
            <h1 class="display-4">TMomentum</h1>
            <p>Track several nasdaq top preforming stocks and view their momentum.</p>
        
            <div>
                <button a class="btn btn-primary" asp-area="" asp-controller="Trade" asp-action="Index">Trade</a></button>
            </div>
        </div>
        <div class="grid-item right-column">
            <!--foreach placeholder-->
            <!--Symbol and Price first row, Info and stock-->
            <div class="grid-layout box">
                <div class="grid-item stock-first">
                    <h2>AAPL</h2>
                    <p class="box-metadata">Rose Quickly</p>
                </div>
                <div class="grid-item stock-second">
                    <p class="mt-1">+1.68%</p>
                    <p class="box-metadata">365.45</p>
                </div>
            </div>
            <div class="grid-layout box">
                <div class="grid-item stock-first">
                    <h2>AAPL</h2>
                    <p class="box-metadata">Rose Quickly</p>
                </div>
                <div class="grid-item stock-second">
                    <p class="mt-1">+1.68%</p>
                    <p class="box-metadata">365.45</p>
                </div>
            </div>
            <div class="grid-layout box">
                <div class="grid-item stock-first">
                    <h2>AAPL</h2>
                    <p class="box-metadata">Rose Quickly</p>
                </div>
                <div class="grid-item stock-second">
                    <p class="mt-1">+1.68%</p>
                    <p class="box-metadata">365.45</p>
                </div>
            </div>

        </div>
    </div>
</section>

track-stock-market-momentum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TMomentum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/ColourScheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/tm.svg" class="logo" />
                    TMomentum</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Togg`le navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Trade" asp-action="Index">Trade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <li class="nav-item colour-btn">
                    <div class="btn-container">
                        <i class="fa fa-sun-o" aria-hidden="true"></i>
                        <label class="switch btn-color-mode-switch">
                            <input type="checkbox" name="color_mode" id="color_mode" value="1">
                            <label for="color_mode" data-on="Dark" data-off="Light" class="btn-color-mode-switch-inner"></label>
                        </label>
                        <i class="fa fa-moon-o" aria-hidden="true"></i>
                    </div>
                    </li>
                </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TMomentum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

track-stock-market-momentum/Views/Trade/Index.cshtml
@model StockTrade

@{
    ViewBag.Title = "Trading";
    ViewBag.CurrentUrl = "~/Trade/Index";
}


<form method="post">
    <div class="box trading-panel">

        <div class="flex trading-panel-flex">
            <div id="stock-price-panel">

                <div class="stock">
                    <h1 class="stock-title">@Model.StockName (@Model.StockSymbol)</h1>
                    <h2 class="stock-price"><small class="text-grey">$</small> <span class="price">@Model.Price.ToString("N")</span></h2>
                </div>

                <div class="date"></div>
            </div>


        </div>
    </div>


    <input type="hidden" name="StockSymbol" id="StockSymbol" value="@Model.StockSymbol" />
    <input type="hidden" id="FinnhubToken" value="@ViewBag.FinnhubToken" />

</form>


@section Scripts {
    @* import the FinnhubScript.js file to update the price *@
    <script src="~/Scripts/FinnhubScript.js">
    </script>
}